# Generated by Django 5.2.1 on 2025-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='danshjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=500)),
                ('dad', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='notebock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameNote', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
